load(pathJoin("PrgEnv-intel", os.getenv("PrgEnv_intel_ver")))
load(pathJoin("intel", os.getenv("intel_ver")))
load(pathJoin("craype", os.getenv("craype_ver")))
load(pathJoin("cray-mpich", os.getenv("cray_mpich_ver")))
load(pathJoin("cray-pals", os.getenv("cray_pals_ver")))
load(pathJoin("cmake", os.getenv("cmake_ver")))

prepend_path("MODULEPATH", os.getenv("modulepath_compiler"))
prepend_path("MODULEPATH", os.getenv("modulepath_mpi"))

load(pathJoin("pnetcdf-D", os.getenv("pnetcdf_ver")))
load(pathJoin("hdf5-D", os.getenv("hdf5_ver")))
load(pathJoin("netcdf-D", os.getenv("netcdf_ver")))
load(pathJoin("libjpeg", os.getenv("libjpeg_ver")))
load(pathJoin("g2", os.getenv("g2_ver")))
load(pathJoin("g2tmpl", os.getenv("g2tmpl_ver")))
load(pathJoin("w3emc", os.getenv("w3emc_ver")))
load(pathJoin("w3nco", os.getenv("w3nco_ver")))
load(pathJoin("libpng", os.getenv("libpng_ver")))
load(pathJoin("bacio", os.getenv("bacio_ver")))
load(pathJoin("jasper", os.getenv("jasper_ver")))
load(pathJoin("zlib", os.getenv("zlib_ver")))
load(pathJoin("wgrib2", os.getenv("wgrib2_ver")))
load(pathJoin("bufr", os.getenv("bufr_ver")))

--prepend_path("MODULEPATH", os.getenv("modulepath_grib"))
load(pathJoin("grib_util", os.getenv("grib_util_ver")))
load(pathJoin("prod_util", os.getenv("prod_util_ver")))
